# Generated by Django 4.1.7 on 2023-02-23 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
