# Generated by Django 4.1.7 on 2023-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todoitem_options_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
