# Generated by Django 4.1.7 on 2023-02-24 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_todoitem_options_alter_todoitem_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['start_date', 'end_date']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
