# Generated by Django 4.1.7 on 2023-02-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='start_date',
        ),
    ]
